### ISSUE TITLE
As a user, I want my display to turn into a "Portal"

### ISSUE THREAD

**Issue by labofoz** [labofoz/handsfree.js#37]
![iphonex-optical-illusion-thevoid_gif_1](https://user-images.githubusercontent.com/42591975/49236175-663f0580-f3b0-11e8-84c7-9d540df30809.gif)

Let’s try and recreate this [VR Display](https://github.com/algomystic/TheParallaxView), which would open up:

- New ways to consume educational content
- New types of games
- Begin to introduce manipulation of 3D environments handsfree

Here are the proposed steps:

- Use aframe.io to quickly scaffold a scene
- Use handsfree.js to move the scene when you do

Here is my first experiment with Aframe: https://glitch.com/edit/#!/magic-window

Here are some more example videos:
- [WiiMote Hack with Johnny Lee](https://www.youtube.com/watch?v=Jd3-eiid-Uw)
- [DSi](https://www.youtube.com/watch?v=h5QSclrIdlE)
- [HoloToy](https://www.youtube.com/watch?v=NvCHHUN8nnE)
- [i3D](https://www.youtube.com/watch?v=7saRtCUgbNI)
- [VR with Face Tracking](https://www.youtube.com/watch?v=Gv8nwCHQ_-w)
- [Ghost Protocol "Hallway" scene](https://www.youtube.com/watch?v=ydIPKkjBlMw)

---
## Tasks
- [x] Create a "PlayCanvasPortal" plugin
- [x] Create a "PlayCanvas Portal" route
- [x] Get PlayCanvas to display fullscreen in the route, and disable the boids wallpaper
- [x] Give it "[Magic Window](https://glitch.com/~magic-window" controls
- ~~Calculate the [projection matrix](https://forum.playcanvas.com/t/solved-how-to-use-camera-calculateprojection-properly/5624) based on where the user is on the screen (we may need an actual tape measure)~~
- ~~[Follow instructions here](http://www.anxious-bored.com/blog/2018/2/25/theparallaxview-illusion-of-depth-by-3d-head-tracking-on-iphone-x) to create effect~~

## Tasks updated
This has proven to be very difficult, especially since I'm trying to reproduce a very complex scene (complex to me). Instead let's build from this demo: http://auduno.tumblr.com/post/25125149521/head-tracking-with-webrtc

- [ ] Add Three.js as a dependency
- [ ] Create the Three scene
- [ ] Copy/Paste their demo and replace it with handsfree.js
- [ ] Make any improvements and tweak the scene to look nicer

**Comment by labofoz** [comment]
Let's create this as a PlayCanvas plugin. This would allow people to easily create "portal experiences" in the browser, or simply set the projection of any existing PlayCanvas game!

**Comment by labofoz** [comment]
Since I'm just trying to build a demo, I'm going to back off of PlayCanvas for now. Instead I'm going to try and implement this demo: https://vimeo.com/44049736

Described here: http://auduno.tumblr.com/post/25125149521/head-tracking-with-webrtc

With source: https://github.com/auduno/headtrackr

This uses Three.js which will allow me to learn from basic principles
