### ISSUE TITLE
Let's add PoseNet support with handsfree.poses[n].head

### ISSUE THREAD

**Issue by labofoz** [labofoz/handsfree.js#53]
![](https://camo.githubusercontent.com/c9da79fc2c7c887dff052f31eba3482e1690c0df/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f35357673495442524b526c616f73464b37492f67697068792e676966)

Most of the previous logic from the [PoseNet prototype](https://github.com/BrowseHandsfree/handsfree-old-posenet) should be easy to port over. This task deals with exposing a working `handsfree.pose[n].head` API, which can either work with or substitute the `handsfree.pose[n].face` API.

The problem with the face tracker is that it requires you to be looking at the computer (since it's a face tracker 😅). This works well for devices with screens, but Handsfree.js can also work on things without screens, like [Google AIY Kits](https://aiyprojects.withgoogle.com/). Another use case is for interfacing with projected displays (where the camera is opposite the screen), like at a conference or in a classroom.

Let's just focus on the head for now, since most of the face code will work well.

## Tasks
- [ ] Load PoseNet model
- [ ] Show debug
- [ ] Toggle model via instantiation config
- [ ] Move cursor
- [ ] Disable/Enable the model post-instantiation
- [ ] Test

## Demos
- [ ] Autoswapping - When I'm facing the camera the face API is used, if no face is detected then the head API is used instead. Inspired from this project: https://twitter.com/cassiecodes/status/1008382429629952000
- [ ] Swap between face and head APIs with a gesture (shaking head "no" for example to switch)

## Blogs
- [ ] How to use the API
- [ ] How to use both the `face` and `head` APIs together
- [ ] When to prefer `head` over `face`
- [ ] Benchmarks
