### ISSUE TITLE
Let's start exploring healthcare by detecting heart beats

### ISSUE THREAD

**Issue by labofoz** [labofoz/handsfree.js#54]
Since we already have the webcam on, let's start integrating handsfree.js with various ML healthcare techniques. This will help us create "Handsfree Deep Learning Starter Kits" (so that people can use Handsfree.js to quickly discover new use cases, like predictive typing, sub-pixel gesture recognition, and more)

I've recently started joining social networks in other languages to see what people are up to around the world and I found this example of detecting heart beats in the browser:

Sources 1: https://qiita.com/taichi-iki/items/0b9165deab187bb2d3f9
Source 2: https://qiita.com/ohtaman/items/2fcbd76567ad000e4055
![68747470733a2f2f71696974612d696d6167652d73746f72652e73332e616d617a6f6e6177732e636f6d2f302f3135323530382f63313333633536352d343263332d313630372d303865632d3239326461653262363964632e706e67](https://user-images.githubusercontent.com/42591975/51207255-29c35c80-18bf-11e9-8728-0d29702eb551.png)

This still needs planning, but the general idea is to:

## Tasks
- [ ] Fork demo and replace their trackers with ours, ensuring to use the same video stream and tracker (BRFv4 or PoseNet)
- [ ] Add a "Turn on Heart Beat Detection" setting to https://handsfree.js.org/#/settings
- [ ] Turn this into a plugin

## Social
- [ ] Shoot demo video
- [ ] Write a how to post
