### ISSUE TITLE
Let's create a debug route, to help us with creating gesture APIs

### ISSUE THREAD

**Issue by labofoz** [labofoz/handsfree.js#67]
In order to better understand how to calculate gestures, it'll be helpful to have a debug screen of some kind that shows us all of the pose data at a glance. Let's keep this route simple for now:

- [x] Create a `/debug` route
- [x] Display head translation, rotation, scale
- [x] Show event states for smiles gesture (currently mapped to onMouseDown|Drag|Up)

## The "Debugger"
The debugger - which is composed of a canvas over the video feed - serves several purposes:
- It helps us visually inspect what the camera sees, which is helpful for troubleshooting
- It can be used by creative coders to apply things over the face out-the-box
- It'll be helpful for creating streams/tutorials

### Tasks
- [x] Remove debugger option from `/settings`...
- [x] ...and add it to `/debug` under the title card
- [x] Remove the FPS counter and attach it to the left of the previewer
- [x] Add some content describing the purpose of the debugger and how to move and resize it
- [x] Record demo GIF

**Comment by labofoz** [comment]
![image](https://user-images.githubusercontent.com/42591975/53194964-7b02f200-35c9-11e9-89ad-85849a0098a3.png)

Finished for now. This route isn't terribly useful yet other than for showing the live preview, but will become much more useful once we add a live code/plugin editor to the site!
